# Generated by Django 3.2.5 on 2021-07-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='champion_class',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='champion',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='champion',
            name='talent',
            field=models.CharField(max_length=100),
        ),
    ]
