# Generated by Django 3.2.5 on 2021-07-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20210715_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionClassImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_class_name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='championimage',
            name='champion_name',
            field=models.CharField(max_length=50),
        ),
    ]
