# Generated by Django 3.2.5 on 2021-07-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20210715_2145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChampionClassImage',
        ),
        migrations.DeleteModel(
            name='ChampionImage',
        ),
        migrations.AddField(
            model_name='champion',
            name='champion_class_image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='champion',
            name='champion_image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
