# Generated by Django 3.2.5 on 2021-07-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_championmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='championmap',
            name='confidence_interval_minus',
            field=models.IntegerField(default=0),
        ),
    ]
