# Generated by Django 3.2 on 2021-06-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='totalReactions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
