# Generated by Django 3.2 on 2021-06-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210620_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postreaction',
            old_name='reactionType',
            new_name='reaction_type',
        ),
        migrations.AlterField(
            model_name='post',
            name='totalReactions',
            field=models.IntegerField(default=0),
        ),
    ]
