# Generated by Django 3.2.5 on 2021-07-11 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210621_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='blog.post'),
        ),
    ]
